; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
label-mode-padding = 1
label-mode-background = ${colors.background-alt}
label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline = ${colors.primary}
label-focused-padding = 1
label-unfocused = %index%
label-unfocused-padding = 1
label-unfocused-foreground = ${colors.disabled}
label-visible = %index%
label-visible-background = ${colors.background}
label-visible-underline = ${colors.disabled}
label-visible-padding = 1
label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

[module/menu-apps]
type = custom/text
content = "  "
content-background = ${colors.background-alt}
content-foreground = ${colors.primary}
click-left = rofi -show drun -theme catppuccin-default

[module/xwindow]
type = internal/xwindow
label = " %title:0:60:...%"
label-foreground = ${colors.disabled}

[module/date]
type = internal/date
interval = 1
date = %Y-%m-%d | %H:%M:%S
date-alt = %B/%d/%Y %A | %H:%M:%S
label = %date%
label-foreground = ${colors.subtext1}

[module/systray]
type = internal/tray
format-margin = 4pt
tray-spacing = 8pt

[module/mpd]
type = internal/mpd
; Host where mpd is running (either ip or domain name)
; Can also be the full path to a unix socket where mpd is running.
host = 127.0.0.1
port = 6600
password = ""
; Seconds to sleep between progressbar/song timer sync
interval = 1
;   <toggle> - gets replaced with <icon-(pause|play)>
;   <toggle-stop> - gets replaced with <icon-(stop|play)>
;   <icon-single> - Toggle playing only a single song. Replaces <icon-repeatone>
format-online = <label-song> <bar-progress> <label-time> <icon-prev> <icon-stop> <toggle> <icon-next> <icon-repeat> <icon-random>
;format-playing = ${self.format-online}
;format-playing = ${self.format-online}
;format-paused = ${self.format-online}
;format-stopped = ${self.format-online}
format-offline = <label-offline>
; Available tokens:
;   %artist%
;   %album-artist%
;   %album%
;   %date%
;   %title%
; label-song =  %artist% - %title%
label-song = %{F#cba6f7} %title%
label-time = %elapsed% / %total%
label-offline = 󰒎 Mpd Offline
label-offline-foreground = ${colors.disabled}
; Only applies if <icon-X> is used
icon-play       = %{F#89b4fa}
icon-pause      = %{F#89b4fa}
icon-stop       = %{F#89b4fa}
icon-prev       = %{F#89b4fa}󰒮
icon-next       = %{F#89b4fa}󰒭
icon-seekb      = %{F#89b4fa}
icon-seekf      = %{F#89b4fa}
icon-random     = %{F#89b4fa}
icon-repeat     = %{F#89b4fa}
icon-repeatone  = %{F#89b4fa}
icon-single     = %{F#89b4fa}
icon-consume    = %{F#89b4fa}󰥠
; Used to display the state of random/repeat/repeatone/single
; Only applies if <icon-[random|repeat|repeatone|single]> is used
toggle-on-foreground = ${colors.primary}
toggle-off-foreground = ${colors.primary}
; Only applies if <bar-progress> is used
bar-progress-width      = 10
bar-progress-indicator  = %{F#89dceb}|
bar-progress-fill       = %{F#89dceb}─
bar-progress-empty      = %{F#585b70}─%{F-}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true
interval = 5
reverse-scroll = false
format-volume = <label-volume>
format-muted = <label-muted>
label-volume = %percentage%%
label-muted = "󰖁 %percentage%%"
label-muted-foreground = ${colors.disabled}
format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = ${colors.primary}
; Right and Middle click
; click-right = pavucontrol
; click-middle = 

; Need write permission
[module/backlight]
type = internal/backlight
; $ ls -1 /sys/class/backlight/
card = nvidia_0
; Use the `/sys/class/backlight/.../actual-brightness` file
use-actual-brightness = true
; Default: 0 (5 if use-actual-brightness is false)
poll-interval = 0
; write to `/sys/class/backlight/${self.card}/brightness` which requires polybar to have write access to that file. DO NOT RUN POLYBAR AS ROOT. 
enable-scroll = false
; Default: 5
scroll-interval = 10
; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp> <label>
;   %percentage% (default)
label = %percentage%%
; Only applies if <ramp> is used
ramp-0 = 󰃚
ramp-1 = 󰃛
ramp-2 = 󰃜
ramp-3 = 󰃝
ramp-4 = 󰃞
ramp-foreground = ${colors.primary}
; Only applies if <bar> is used
bar-width = 10
bar-indicator = |
bar-fill = ─
bar-empty = ─

[module/battery]
type = internal/battery
full-at = 100
low-at = 20
battery = BAT0
adapter = ADP1
poll-interval = 5
format-charging = <animation-charging> <label-charging>
format-charging-foreground = ${colors.green}
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-foreground = ${colors.green}
format-full = <ramp-capacity> <label-full>
format-full-foreground = ${colors.green}
format-low = <label-low> <animation-low>
format-low-foreground = ${colors.red}
; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
; Framerate in milliseconds
animation-charging-framerate = 1000
; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 1000
; Only applies if <animation-low> is used
; New in version 3.6.0
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200
; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
; Only applies if <bar-capacity> is used
bar-capacity-width = 10
; text
label-charging = %percentage%%
label-charging-foreground = ${colors.text}
label-discharging = %percentage%%
label-discharging-foreground = ${colors.text}
label-full = %percentage_raw%%
label-full-foreground = ${colors.text}
label-low = %percentage_raw%%
label-low-foreground = ${colors.text}

[module/filesystem]
type = internal/fs
interval = 30
mount-0 = /
label-mounted = "%{F#f2cdcc}󰋊%{F-} %percentage_used%%"
label-mounted-foreground = ${colors.text}
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = ""
format-prefix-foreground = ${colors.mauve}
label = %percentage:2%%

[module/temperature]
type = internal/temperature
; Seconds to sleep between updates Default: 1
interval = 2
; run $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 0
; The name has to match the contents of /sys/class/thermal/thermal_zone*/type
; Default: ""
zone-type = x86_pkg_temp
; Full path of temperature sysfs path
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input
; Base temperature for where to start the ramp (in degrees celsius)
base-temperature = 0
; Threshold temperature to display warning label (in degrees celsius)
warn-temperature = 80
units = true
format = <ramp> <label>
format-warn = <ramp> <label-warn>
; Available tokens:
;   %temperature% (deprecated)
;   %temperature-c%   (default, temperature in °C)
;   %temperature-f%   (temperature in °F)
;   %temperature-k%   (temperature in Kelvin, new in version 3.7.0)
label = %temperature-c%
; Available tokens:
;   %temperature% (deprecated)
;   %temperature-c%   (default, temperature in °C)
;   %temperature-f%   (temperature in °F)
;   %temperature-k%   (temperature in Kelvin, new in version 3.7.0)
label-warn = %temperature-c%
label-warn-foreground = ${colors.alert}
; Requires the <ramp> tag
; The icon selection will range from `base-temperature` to `warn-temperature`,
; temperatures at and above `warn-temperature` will use the last icon
; and temperatures at and below `base-temperature` will use `ramp-0`. 
; All other icons are distributed evenly between the two temperatures.
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.maroon}

[module/memory]
type = internal/memory
interval = 3
warn-percentage = 90
format = <label>
format-warn = <label-warn>
label = %gb_used%
; label = %gb_used%/%gb_total%
; label = %percentage_used:2%%
label-warn = %gb_used%
label-warn-foreground = ${colors.alert}
format-prefix = " "
format-prefix-foreground = ${colors.mauve}
format-warn-prefix = " "
format-warn-prefix-foreground = ${colors.mauve}

[module/network]
type = custom/script
exec = /bin/sh -c 'ip addr | awk '\''/state UP/ {gsub(":", "", $2); iface=$2} /inet / && !/127.0.0.1/ && iface {split($2, a, "/"); if (iface ~ /wlan/) {cmd="iwctl station " iface " show | grep \"Connected network\" | tr -s \" \" | cut -d \" \" -f4 "; cmd | getline ssid; close(cmd); print "%{F#74c7ec} %{F#cdd6f4}" ssid " %{F#a6adc8}" a[1]; exit} else {print "%{F#74c7ec} %{F#cdd6f4}" iface " %{F#a6adc8}" a[1]; exit} } '\'' '
interval = 5
format = <label>
label = %output%

[settings]
screenchange-reload = true
pseudo-transparency = true
# compositing-background = source
# compositing-foreground = over

; vim:ft=dosini

;=======================================================

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

; xrandr brightness through software, which may loss color accuracy
[module/xbacklight]
type = internal/xbacklight
; XRandR output to get get values from
; Default: the monitor defined for the running bar
output = DP-4
; Default: true
enable-scroll = false
format = <ramp> <label>
label = %percentage%%
; Only applies if <ramp> is used
ramp-0 = 󰃞
ramp-1 = 󰃝
ramp-2 = 󰃜
ramp-3 = 󰃛
ramp-4 = 󰃚
ramp-foreground = ${colors.primary}
; Only applies if <bar> is used
bar-width = 10
bar-indicator = |
bar-fill = ─
bar-empty = ─

[module/xworkspaces]
type = internal/xworkspaces
index-sort = true
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%
label-layout-foreground = ${colors.primary}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}
