# Show all
full

# Layout
Legacy_layout=false
background_alpha=0.4
font_size=12

# single enable
# fps
# frametime
# cpu_stats
# gpu_stats
# ram
# vram
# core_load
# gpu_core_clock
# gpu_mem_clock
# gpu_temp
# cpu_temp
